-- =====================================================
-- iRoom Database - Initial Baseline Migration
-- =====================================================
-- This baseline migration is intentionally empty because
-- Flyway is configured with baseline-on-migrate=true.
--
-- The actual table creation is in V2__Create_all_tables.sql
--
-- This migration serves as version 0 (the baseline) and
-- Flyway will start executing from V2 onwards.
-- =====================================================

-- Baseline version - no SQL to execute
-- V2 migration will create all tables

-- =====================================================
-- Existing Tables (documented for reference):
-- =====================================================
--
-- Core Tables:
-- - University: Universities in the system
-- - Department: Academic departments
-- - User: Professors and users
-- - Admin: System administrators
-- - UserType: User role types
-- - Password: User authentication
--
-- Course Management:
-- - Course: Course catalog
-- - Semester: Academic semesters
-- - SemesterCourse: Courses per semester
-- - CourseProfessor: Course-professor assignments
-- - Kateuthinsi: Academic tracks/specializations
-- - CourseKateuthinsi: Course-track relationships
-- - CourseDepart: Course-department relationships
-- - MyCourse: Student course enrollments
--
-- Room Management:
-- - Room: Available rooms
-- - Equipment: Equipment catalog
-- - EquipmentRoom: Room-equipment assignments
-- - RoomDepart: Room-department assignments
-- - EquipmentDepart: Equipment-department assignments
--
-- Scheduling:
-- - Day: Days of the week
-- - Hour: Time slots
-- - Schedule: Scheduling periods
-- - Programme: Main schedule entries
-- - ProgrammeRooms: Room assignments for schedule entries
-- - ProgrammeHistory: Schedule change history
-- - ProgrammeRoomsHistory: Room assignment history
--
-- Exam Scheduling:
-- - ExamDay: Exam dates
-- - ExamProgramme: Exam schedule entries
-- - ExamProgrammeRooms: Room assignments for exams
--
-- System:
-- - Notification: Room booking requests and notifications
-- - AdminSem: Admin-semester assignments
--
-- =====================================================

-- This migration intentionally left empty.
-- The database schema is already in place.
-- All future schema changes should be added as new migrations.
